// Primitive tokens — raw design scale
export const primitive = {
  color: {
    cammello: '#C19A6B',
    marroncaldo: '#6B4F3A',
    testadimoro: '#3E2C20',
    avorio: '#F5F0E6',
    sabbia: '#E8DFD0',
    nero: '#1A1A1A',
    antracite: '#2D2D2D',
    oro: '#B8975A',
    bianco: '#FFFFFF',
    'grigio-100': '#F7F5F2',
    'grigio-200': '#E5E0D9',
    'grigio-300': '#C4BDB3',
    'grigio-400': '#9B9389',
    'grigio-500': '#736B61',
  },
  font: {
    display: "'Cormorant Garamond', 'Georgia', serif",
    body: "'Inter', 'Helvetica Neue', 'Arial', sans-serif",
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '2rem',
    '4xl': '2.5rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '5rem',
  },
  fontWeight: {
    light: '300',
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
  },
  lineHeight: {
    tight: '1.1',
    snug: '1.25',
    normal: '1.5',
    relaxed: '1.625',
    loose: '1.8',
  },
  letterSpacing: {
    tighter: '-0.03em',
    tight: '-0.015em',
    normal: '0',
    wide: '0.025em',
    wider: '0.05em',
    widest: '0.1em',
  },
  spacing: {
    px: '1px',
    0.5: '0.125rem',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
    10: '2.5rem',
    12: '3rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    32: '8rem',
    40: '10rem',
    48: '12rem',
  },
  radius: {
    none: '0',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    full: '9999px',
  },
  duration: {
    fast: '150ms',
    normal: '300ms',
    slow: '500ms',
    slower: '800ms',
  },
  easing: {
    default: 'cubic-bezier(0.25, 0.1, 0.25, 1)',
    in: 'cubic-bezier(0.55, 0.055, 0.675, 0.19)',
    out: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    inOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  },
} as const;

// Semantic tokens — design intent
export const semantic = {
  color: {
    surface: {
      primary: 'var(--color-avorio)',
      secondary: 'var(--color-sabbia)',
      tertiary: 'var(--color-grigio-100)',
      inverse: 'var(--color-nero)',
      brand: 'var(--color-cammello)',
    },
    ink: {
      primary: 'var(--color-testadimoro)',
      secondary: 'var(--color-marroncaldo)',
      tertiary: 'var(--color-grigio-500)',
      inverse: 'var(--color-avorio)',
      brand: 'var(--color-cammello)',
      link: 'var(--color-marroncaldo)',
    },
    accent: {
      primary: 'var(--color-cammello)',
      secondary: 'var(--color-oro)',
      hover: 'var(--color-marroncaldo)',
    },
    line: {
      subtle: 'var(--color-grigio-200)',
      default: 'var(--color-grigio-300)',
      strong: 'var(--color-marroncaldo)',
    },
    focus: {
      ring: 'var(--color-cammello)',
    },
  },
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
  },
  text: {
    display: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(2.5rem, 5vw + 1rem, 5rem)',
      fontWeight: 'var(--fontWeight-light)',
      lineHeight: 'var(--lineHeight-tight)',
      letterSpacing: 'var(--letterSpacing-tight)',
    },
    h1: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(2rem, 3vw + 0.5rem, 3.5rem)',
      fontWeight: 'var(--fontWeight-light)',
      lineHeight: 'var(--lineHeight-tight)',
      letterSpacing: 'var(--letterSpacing-tight)',
    },
    h2: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(1.5rem, 2vw + 0.5rem, 2.5rem)',
      fontWeight: 'var(--fontWeight-regular)',
      lineHeight: 'var(--lineHeight-snug)',
      letterSpacing: 'var(--letterSpacing-normal)',
    },
    h3: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(1.25rem, 1.5vw + 0.25rem, 2rem)',
      fontWeight: 'var(--fontWeight-regular)',
      lineHeight: 'var(--lineHeight-snug)',
      letterSpacing: 'var(--letterSpacing-normal)',
    },
    body: {
      fontFamily: 'var(--font-body)',
      fontSize: 'clamp(1rem, 0.5vw + 0.875rem, 1.125rem)',
      fontWeight: 'var(--fontWeight-regular)',
      lineHeight: 'var(--lineHeight-relaxed)',
      letterSpacing: 'var(--letterSpacing-normal)',
    },
    caption: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--fontSize-sm)',
      fontWeight: 'var(--fontWeight-regular)',
      lineHeight: 'var(--lineHeight-normal)',
      letterSpacing: 'var(--letterSpacing-wide)',
    },
    label: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--fontSize-xs)',
      fontWeight: 'var(--fontWeight-medium)',
      lineHeight: 'var(--lineHeight-normal)',
      letterSpacing: 'var(--letterSpacing-widest)',
      textTransform: 'uppercase' as const,
    },
  },
} as const;

// Component tokens — block-specific
export const component = {
  hero: {
    minHeight: '90vh',
    paddingBlock: 'var(--spacing-24)',
    titleColor: 'var(--ink-primary)',
    subtitleColor: 'var(--ink-secondary)',
    bgColor: 'var(--surface-primary)',
  },
  narrative: {
    paddingBlock: 'var(--spacing-20)',
    maxWidth: '72ch',
    textColor: 'var(--ink-primary)',
    bgColor: 'var(--surface-primary)',
  },
  frontBackStage: {
    paddingBlock: 'var(--spacing-16)',
    dividerColor: 'var(--line-subtle)',
    customerBg: 'var(--surface-primary)',
    adobeBg: 'var(--surface-secondary)',
    chipBg: 'var(--surface-tertiary)',
    chipBorder: 'var(--line-default)',
    chipText: 'var(--ink-secondary)',
  },
  journeyPhase: {
    paddingBlock: 'var(--spacing-16)',
    bgColor: 'var(--surface-secondary)',
    accentColor: 'var(--accent-primary)',
    titleColor: 'var(--ink-primary)',
  },
  persona: {
    paddingBlock: 'var(--spacing-16)',
    cardBg: 'var(--surface-secondary)',
    cardRadius: 'var(--radius-lg)',
    nameColor: 'var(--ink-primary)',
    detailColor: 'var(--ink-secondary)',
  },
  productGateway: {
    paddingBlock: 'var(--spacing-16)',
    bgColor: 'var(--surface-primary)',
    cardBg: 'var(--surface-secondary)',
    cardHoverBg: 'var(--surface-tertiary)',
  },
  adobeStackReveal: {
    paddingBlock: 'var(--spacing-20)',
    bgColor: 'var(--surface-inverse)',
    textColor: 'var(--ink-inverse)',
    accentColor: 'var(--accent-secondary)',
  },
  metric: {
    paddingBlock: 'var(--spacing-12)',
    numberColor: 'var(--accent-primary)',
    labelColor: 'var(--ink-secondary)',
    bgColor: 'var(--surface-secondary)',
  },
  timeline: {
    paddingBlock: 'var(--spacing-20)',
    lineColor: 'var(--line-default)',
    dotColor: 'var(--accent-primary)',
    bgColor: 'var(--surface-primary)',
  },
  nav: {
    height: '4rem',
    bgColor: 'var(--surface-primary)',
    borderColor: 'var(--line-subtle)',
    linkColor: 'var(--ink-primary)',
    linkHoverColor: 'var(--accent-primary)',
    activeColor: 'var(--accent-primary)',
  },
  footer: {
    paddingBlock: 'var(--spacing-12)',
    bgColor: 'var(--surface-inverse)',
    textColor: 'var(--ink-inverse)',
    linkColor: 'var(--accent-secondary)',
  },
} as const;
