import type { AssetSlot } from '@edf/core/assets/types';

export const assets: AssetSlot[] = [
  {
    id: 'bg-citta',
    type: 'stock',
    query: 'italian city street evening people walking warm light atmosphere',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-due-mondi',
    type: 'stock',
    query: 'abstract light split contrast dark bridge connection minimal architecture',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-dati',
    type: 'stock',
    query: 'abstract data network nodes dark background technology connection lines',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-filiale',
    type: 'stock',
    query: 'modern office consultation meeting professional interior warm light',
    aspect: '16:9',
    width: 2400,
    grade: 'editorial',
    alt: '',
  },
  {
    id: 'bg-orizzonte',
    type: 'stock',
    query: 'horizon dawn light road forward minimal landscape hope',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-dashboard',
    type: 'stock',
    query: 'analytics dashboard monitor dark office data screen professional',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'persona-elisa',
    type: 'stock',
    query: 'young woman smartphone cafe natural light thoughtful portrait',
    aspect: '4:5',
    width: 900,
    grade: 'editorial',
    alt: 'Elisa — cliente che valuta un prestito personale dal suo smartphone',
  },
];
