import type { AssetSlot } from '@edf/core/assets/types';

export const assets: AssetSlot[] = [
  {
    id: 'bg-stazione',
    type: 'stock',
    query: 'modern railway station interior architecture steel light perspective travel',
    aspect: '16:9',
    width: 2400,
    grade: 'editorial',
    alt: '',
  },
  {
    id: 'bg-binari',
    type: 'stock',
    query: 'railway tracks night LED lights perspective atmospheric dark minimal',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-dati',
    type: 'stock',
    query: 'abstract data network nodes dark background technology connection lines',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'bg-parcheggio',
    type: 'stock',
    query: 'modern parking garage aerial view urban structure lines symmetry',
    aspect: '16:9',
    width: 2400,
    grade: 'editorial',
    alt: '',
  },
  {
    id: 'bg-viaggio',
    type: 'stock',
    query: 'businessman traveler with luggage train station natural light motion',
    aspect: '16:9',
    width: 2400,
    grade: 'editorial',
    alt: '',
  },
  {
    id: 'bg-dashboard',
    type: 'stock',
    query: 'analytics dashboard monitor dark office data screen professional',
    aspect: '16:9',
    width: 2400,
    grade: 'duotone',
    alt: '',
  },
  {
    id: 'persona-marco',
    type: 'stock',
    query: 'confident bearded businessman glasses suit portrait smiling professional headshot',
    aspect: '4:5',
    width: 900,
    grade: 'editorial',
    alt: 'Davide — pendolare business Milano–Roma',
  },
];
